// Langue de l'interface. Le programme est écrit en français ; quand Windows n'est pas en français (ou que
// le réglage le demande), chaque texte affiché passe par Langue.T, qui le cherche dans le dictionnaire
// ci-dessous. Un texte absent du dictionnaire reste en français : rien ne casse, il manque juste une ligne.
// Les noms internes (ceux de --jouer et des réglages) restent en français dans les deux langues.
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text.RegularExpressions;

namespace MascotteStickman
{
    static class Langue
    {
        static Dictionary<string, string> dico;
        static readonly Regex compte = new Regex(@"^(.*?)  \((\d+)\)$");

        public static bool Force;                               // --anglais sur la ligne de commande (planches du README)

        public static bool Anglais
        {
            get
            {
                if (Force) return true;
                int reglage = (int)R.D("langue");                // 0 : comme Windows, 1 : français, 2 : anglais
                return reglage == 2 || (reglage == 0 && CultureInfo.CurrentUICulture.TwoLetterISOLanguageName != "fr");
            }
        }

        public static string T(string fr) { return Anglais ? EnAnglais(fr) : fr; }

        public static string EnAnglais(string fr)
        {
            if (string.IsNullOrEmpty(fr)) return fr;
            if (dico == null)
            {
                dico = new Dictionary<string, string>();
                for (int i = 0; i + 1 < paires.Length; i += 2) dico[paires[i]] = paires[i + 1];
            }
            string en;
            if (dico.TryGetValue(fr, out en)) return en;
            // textes composés : « bras + jambes » des danses, variantes de l'autre main, familles suivies de leur compte
            int plus = fr.IndexOf(" + ", StringComparison.Ordinal);
            if (plus > 0) return EnAnglais(fr.Substring(0, plus)) + " + " + EnAnglais(fr.Substring(plus + 3));
            foreach (string[] suffixe in suffixes)
                if (fr.EndsWith(suffixe[0], StringComparison.Ordinal)) return EnAnglais(fr.Substring(0, fr.Length - suffixe[0].Length)) + suffixe[1];
            Match m = compte.Match(fr);
            if (m.Success) return EnAnglais(m.Groups[1].Value) + "  (" + m.Groups[2].Value + ")";
            int tiret = fr.IndexOf("  —  ", StringComparison.Ordinal);
            if (tiret > 0) return EnAnglais(fr.Substring(0, tiret)) + "  —  " + EnAnglais(fr.Substring(tiret + 5));
            return fr;
        }

        static readonly string[][] suffixes =
        {
            new[] { " (autre main)", " (other hand)" }, new[] { " (autre jambe)", " (other leg)" }, new[] { " au ralenti", " in slow motion" },
            new[] { "  — tête creuse", "  — ring head" }, new[] { " (tête creuse)", " (ring head)" }, new[] { " (tête pleine)", " (solid head)" },
        };

        static readonly string[] paires =
        {
            // ---------------------------------------------------------------- menus et fenêtre des paramètres
            "Paramètres…", "Settings…",
            "animations", "animations",
            "réglages", "settings",
            "Couleur", "Colour",
            "Arc-en-ciel", "Rainbow",
            "Jouer une animation", "Play an animation",
            "Amis", "Friends",
            "Ajouter un stickman", "Add a stickman",
            "Renvoyer celui-ci", "Send this one away",
            "Aller voir un ami", "Go and see a friend",
            "Danser sur la musique", "Dance to the music",
            "Sauter sur une fenêtre", "Jump onto a window",
            "Se téléporter", "Teleport",
            "Mode farceur : il ferme des fenêtres", "Prank mode: he closes windows",
            "Mode muet (plus aucun bruit)", "Mute (no sound at all)",
            "Correcteur d'orthographe", "Spell checker",
            "Revenir dans le coin", "Back to his corner",
            "Lancer au démarrage de Windows", "Start with Windows",
            "Quitter", "Quit",
            "Remettre cet onglet à zéro", "Reset this tab",
            "Chercher : ", "Search: ",
            "Chercher par nom ou par famille", "Search by name or family",
            "▶ Jouer", "▶ Play",
            "Tout cocher", "Tick all",
            "Tout décocher", "Untick all",
            "À quelle fréquence il choisit chaque famille d'animations (0 = jamais).", "How often he picks each family of animations (0 = never).",
            "affichées", "shown",
            "animations actives sur", "active animations out of",
            "Double-clic pour en essayer une ; décochée, elle n'est plus choisie au hasard.", "Double-click to try one; unticked, it is no longer picked at random.",
            "Rouge", "Red", "Vert", "Green", "Bleu", "Blue", "Jaune", "Yellow", "Violet", "Purple", "Rose", "Pink", "Cyan", "Cyan", "Orange", "Orange",
            "Noir", "Black", "Rouge sombre", "Dark red", "Blanc", "White", "Gris", "Grey", "Turquoise", "Teal", "Or", "Gold", "Citron vert", "Lime", "Bleu nuit", "Navy",

            // ---------------------------------------------------------------- onglets et réglages
            "Apparence", "Appearance", "Mouvement", "Movement", "Comportement", "Behaviour", "Sons", "Sounds", "Souris", "Mouse", "Physique", "Physics",
            "Système", "System", "Familles", "Families", "Spécial", "Special",
            "Langue / Language", "Langue / Language",
            "comme Windows / same as Windows", "comme Windows / same as Windows",
            "Arc-en-ciel (change de couleur en continu)", "Rainbow (keeps changing colour)",
            "Vraies textures de Minecraft (lues dans le jeu installé sur ce PC)", "Real Minecraft textures (read from the game installed on this PC)",
            "Taille", "Size",
            "Épaisseur du trait", "Line thickness",
            "Taille de la tête", "Head size",
            "Longueur du torse", "Torso length",
            "Longueur des bras", "Arm length",
            "Longueur des jambes", "Leg length",
            "Épaisseur du contour", "Outline thickness",
            "Couleur du contour", "Outline colour",
            "Halo lumineux", "Glow",
            "Ombre au sol", "Ground shadow",
            "Opacité (%)", "Opacity (%)",
            "Traînée derrière la main", "Trail behind the hand",
            "Longueur de la traînée", "Trail length",
            "Vitesse de l'arc-en-ciel", "Rainbow speed",
            "Bulles de texte", "Speech bubbles",
            "Accessoires (épée, ballon, notes…)", "Props (sword, ball, notes…)",
            "selon la couleur, comme dans la série", "depends on the colour",
            "toujours pleine", "always solid",
            "toujours creuse (anneau)", "always a ring",
            "Vitesse des animations (%)", "Animation speed (%)",
            "Vitesse de déplacement (%)", "Walking speed (%)",
            "Douceur des transitions (ms)", "Transition smoothness (ms)",
            "Respiration au repos (%)", "Idle breathing (%)",
            "Images par seconde", "Frames per second",
            "Puissance des sauts (%)", "Jump power (%)",
            "Secondes entre deux actions", "Seconds between two actions",
            "Durée des animations (%)", "Animation length (%)",
            "Se promène", "Walks around",
            "Distance des promenades", "Walking distance",
            "Explore tout l'écran (sinon reste près de chez lui)", "Explores the whole screen (otherwise stays near home)",
            "Saute sur le haut des fenêtres", "Jumps onto the top of windows",
            "Envie de sauter sur une fenêtre (%)", "Urge to jump onto a window (%)",
            "Gestes pendant la marche (%)", "Gestures while walking (%)",
            "S'endort après (minutes sans toucher au PC, 0 = jamais)", "Falls asleep after (minutes without using the PC, 0 = never)",
            "Envie de se téléporter : commande, perle de l'Ender ou portail (%)", "Urge to teleport: command, Ender pearl or portal (%)",
            "Le premier stickman a le bâton de commande", "The first stickman carries the command staff",
            "Leur maison reste toujours visible", "Their house always stays visible",
            "CORRECTEUR : il corrige mes fautes d'orthographe (lit le texte près du curseur, jamais les mots de passe)", "SPELL CHECKER: he fixes my typos (reads the text next to the caret, never passwords)",
            "MODE FARCEUR : il ferme des fenêtres en appuyant sur leur croix", "PRANK MODE: he closes windows by pressing their X",
            "Mode farceur : minutes entre deux fermetures", "Prank mode: minutes between two closings",
            "Mode farceur : peut aussi fermer la fenêtre que j'utilise", "Prank mode: may also close the window I am using",
            "Sauts vers les fenêtres", "Jumps towards windows",
            "variés", "varied", "simples", "plain", "toujours en salto", "always a somersault", "atterrissage de héros", "hero landing",
            "Danse en rythme quand le PC joue de la musique (de temps en temps)", "Dances on the beat when the PC plays music (now and then)",
            "Envie de danser quand il y a de la musique (%)", "Urge to dance when music plays (%)",
            "Géant : il grandit d'un coup jusqu'en haut de l'écran et fait fuir les autres", "Giant: he suddenly grows as tall as the screen and scares the others away",
            "Minuscule : il rétrécit et file partout", "Tiny: he shrinks and scurries around",
            "Il dessine sur l'écran", "He draws on the screen",
            "Il ouvre YouTube sur la chaîne d'Alan Becker (ouvre le navigateur)", "He opens Alan Becker's YouTube channel (opens the browser)",
            "Il attrape le curseur au lasso (la souris bouge vraiment)", "He lassoes the mouse cursor (the mouse really moves)",
            "Il secoue la fenêtre où il est perché (la fenêtre bouge vraiment)", "He shakes the window he stands on (the window really moves)",
            "Nombre de stickmen", "Number of stickmen",
            "Ils vont se voir : bonjour, checks, câlins, duels amicaux…", "They visit each other: hello, fist bumps, hugs, friendly duels…",
            "Envie d'aller voir un ami (%)", "Urge to go and see a friend (%)",
            "Couleur du 2e", "Colour of the 2nd", "Couleur du 3e", "Colour of the 3rd", "Couleur du 4e", "Colour of the 4th", "Couleur du 5e", "Colour of the 5th", "Couleur du 6e", "Colour of the 6th",
            "Sons activés", "Sounds on",
            "Volume (%)", "Volume (%)",
            "Sauts, atterrissages, rebonds et chutes", "Jumps, landings, bounces and falls",
            "Quand on l'attrape, le lance ou le bouscule", "When grabbed, thrown or knocked over",
            "Bruitages des animations (coups, épée, énergie, saltos…)", "Animation sounds (hits, sword, energy, flips…)",
            "Téléportation", "Teleporting",
            "Suit le curseur du regard", "Watches the cursor",
            "Se bat avec le curseur quand il s'approche", "Fights the cursor when it comes close",
            "Distance de combat", "Fighting distance",
            "Pause entre deux coups (s)", "Pause between two hits (s)",
            "Suit le curseur", "Follows the cursor",
            "Fuit le curseur", "Runs away from the cursor",
            "Se fait renverser par un curseur rapide", "A fast cursor knocks him over",
            "On peut l'attraper à la souris", "Can be grabbed with the mouse",
            "On peut le lancer", "Can be thrown",
            "Un clic le fait", "A click makes him",
            "saluer", "wave", "sauter", "jump", "danser", "dance", "se battre", "fight", "une animation au hasard", "play a random animation",
            "Gravité (%)", "Gravity (%)",
            "Rebond (%)", "Bounce (%)",
            "Frottement au sol (%)", "Ground friction (%)",
            "Balancement quand on le porte (%)", "Swing when carried (%)",
            "Force du lancer (%)", "Throw strength (%)",
            "Vrilles en l'air (%)", "Spin in the air (%)",
            "Rebondit sur les bords de l'écran", "Bounces off the screen edges",
            "Toujours au premier plan", "Always on top",

            // ---------------------------------------------------------------- bulles
            "Salut !", "Hi!", "Hein ?!", "Huh?!", "Oups !", "Oops!", "Ouf !", "Phew!", "Aaaah !", "Aaaah!", "Aaah !", "Aaah!", "Aïe !", "Ouch!",
            "Yahou !", "Yahoo!", "Whoa !", "Whoa!", "Ooooh !", "Ooooh!", "Pfiou !", "Phew!", "Couic !", "Squeak!", "GRAOUH !", "ROAAAR!",
            "Hé !", "Hey!", "Hé hé hé…", "Heh heh heh…", "Facile.", "Easy.", "Il fait bon.", "Nice and warm.", "Élytres !", "Elytra!",
            "Regarde ça !", "Watch this!", "Ça secoue !", "Shake it!", "Elle résiste…", "It won't close…", "Trop tard…", "Too late…",
            "Me revoilà !", "I'm back!", "Ah, ça va mieux.", "Ah, that's better.", "Et voilà la maison !", "And there's the house!",
            "Pas mal, non ?", "Not bad, eh?", "Oh ! Une faute.", "Oh! A typo.", "« {0} », voilà !", "\"{0}\", there you go!",
            "Tiens, je te le rends.", "Here, have it back.", "Hé, viens par là !", "Hey, come over here!",
            "Solide, cette fenêtre.", "Sturdy window.", "Ouf, c'était grand là-haut.", "Phew, it was big up there.",
            "Déjà la nuit ? Bonne nuit…", "Night already? Good night…", "[Stickman] Salut tout le monde !", "[Stickman] Hello everyone!",
            "Allons voir la chaîne d'Alan Becker !", "Let's visit Alan Becker's channel!", "Pas de navigateur ?", "No browser?",
            "Il me faut le bâton de commande !", "I need the command staff!", "Il me faut une fenêtre !", "I need a window!",
            "Aucune fenêtre où m'asseoir", "No window to sit on", "Aucune fenêtre où sauter", "No window to jump onto",
            "Je ne trouve pas cette fenêtre", "I can't find that window", "Pas de fenêtre à secouer…", "No window to shake…",
            "Je n'entends pas de musique…", "I can't hear any music…", "Je suis tout seul…", "I'm all alone…",
            "Personne n'est libre", "Nobody is free", "Personne n'est libre…", "Nobody is free…", "Personne à appeler…", "Nobody to call…",
            "On est déjà six !", "There are six of us already!", "Chut… je ne fais plus de bruit", "Shh… I'll be quiet now", "Le son est revenu !", "Sound is back!",
            "Hé hé… gare à tes fenêtres !", "Heh heh… watch your windows!", "D'accord, je ne touche plus à rien", "All right, I won't touch anything",
            "Je surveille tes fautes (je ne garde rien de ce que tu écris)", "I'm watching your spelling (I keep nothing of what you type)",
            "D'accord, j'arrête de relire", "All right, I'll stop proofreading",

            // ---------------------------------------------------------------- familles
            "Déplacements", "Moving around", "Danses", "Dances", "Gestes", "Gestures", "Combat", "Fighting", "Acrobaties", "Acrobatics", "Sport", "Sport",
            "Quotidien", "Everyday life", "Émotions", "Emotions", "Fenêtres", "Windows", "Minecraft", "Minecraft", "Commandes", "Commands", "Décor", "Scenery",

            // ---------------------------------------------------------------- animations à deux
            "Bonjour", "Hello", "Hé, salut !", "Hey, hi!", "Check", "Fist bump", "Check !", "Bump!", "Tope-là", "High five", "Tope là !", "High five!", "Yeah !", "Yeah!",
            "Poignée de main", "Handshake", "Enchanté !", "Nice to meet you!", "Ça va ?", "How are you?", "Check complet", "Full handshake", "Yo !", "Yo!", "Trop stylé !", "So cool!",
            "Câlin !", "Hug!", "Pierre-feuille-ciseaux", "Rock paper scissors", "Pierre, feuille, ciseaux !", "Rock, paper, scissors!", "…ciseaux !", "…scissors!",
            "Gagné !", "I win!", "Oh non…", "Oh no…", "Duel amical", "Friendly duel", "En garde !", "En garde!", "Viens !", "Come on!", "Bien joué !", "Well played!",
            "Coude contre coude", "Elbow bump", "Coude !", "Elbow!", "Double tope", "Double high five", "Des deux mains !", "Both hands!", "Allez !", "Go!", "Encore !", "Again!",
            "Révérence", "Bow", "Après vous.", "After you.", "Mais non, après vous !", "No, no, after you!", "Danse à deux", "Dance together", "On danse ?", "Shall we dance?", "Carrément !", "Totally!",

            // ---------------------------------------------------------------- danses : bras, puis jambes
            "Boxe", "Boxing", "Bras qui se balancent", "Swaying arms", "Brasse", "Breaststroke", "Cadres", "Frames", "Clap haut-bas", "Clap high and low", "Dab", "Dab",
            "Déhanché", "Hip sway", "Disco", "Disco", "Égyptien", "Egyptian", "Essuie-glaces", "Wipers", "Fièvre du samedi soir", "Saturday night", "Floss", "Floss",
            "Guitare", "Air guitar", "Hélicoptère", "Helicopter", "Lasso", "Lasso", "Macarena", "Macarena", "Mains en l'air", "Hands up", "Manivelle", "Crank",
            "Maracas", "Maracas", "Moulinets", "Windmills", "Papillon", "Butterfly", "Poings en l'air", "Fists up", "Pointe gauche-droite", "Point left and right",
            "Pom-pom", "Pom-poms", "Poulet", "Chicken", "Robot", "Robot", "Roulé d'épaules", "Shoulder roll", "Rouleau", "Roll", "Tape des cuisses", "Thigh slap",
            "Tape des mains", "Clap", "Twist des bras", "Arm twist", "Vague", "Wave", "Vague à deux bras", "Two-arm wave", "YMCA", "YMCA",
            "coups de pied", "kicks", "course sur place", "running on the spot", "pas chassés", "side steps", "rebond", "bounce", "sauts", "jumps", "squats", "squats",
            "talons", "heels", "twist", "twist",

            // ---------------------------------------------------------------- animations
            "/effect : lévitation", "/effect: levitation", "/effect : vitesse", "/effect: speed", "/fill : fait apparaître la maison", "/fill: makes the house appear",
            "/gamemode : vole en créatif", "/gamemode: flies in creative", "/give : une épée en diamant", "/give: a diamond sword", "/particle : des cœurs", "/particle: hearts",
            "/say : salue tout le monde", "/say: greets everyone", "/setblock : pose un bloc", "/setblock: places a block", "/summon : la foudre", "/summon: lightning",
            "/summon : un feu d'artifice", "/summon: a firework", "/summon : une TNT", "/summon: TNT", "/time : la nuit", "/time: night", "/tp : se téléporte", "/tp: teleports",
            "/tp @a : appelle toute la bande", "/tp @a: calls the whole gang", "/weather : la pluie", "/weather: rain",
            "À cloche-pied", "Hopping on one foot", "À genoux", "Kneeling", "A le hoquet", "Has the hiccups", "À quatre pattes", "On all fours", "Abdos", "Sit-ups",
            "Admire un diamant", "Admires a diamond", "Allongé au bord, un bras dans le vide", "Lying on the edge, one arm dangling", "Allongé, bras sous la tête", "Lying down, arms behind his head",
            "Amour", "Love", "Applaudit", "Claps", "Applaudit en sautillant", "Claps while hopping", "Applaudit lentement", "Slow clap", "Arrose des fleurs", "Waters flowers",
            "Arroseur automatique", "Sprinkler", "Assis au bord, balance les jambes", "Sitting on the edge, swinging his legs", "Assis au bord, rêvasse", "Sitting on the edge, daydreaming",
            "Assis jambes tendues", "Sitting with legs stretched", "Assis, balance les pieds", "Sitting, swinging his feet", "Attend le bus", "Waits for the bus",
            "Attrape le curseur au lasso", "Lassoes the cursor", "Avance à la lanterne", "Walks with a lantern", "Bâille", "Yawns", "Balaie", "Sweeps", "Balayage", "Leg sweep",
            "Balaye de la main", "Brushes it off", "Balayette", "Low sweep", "Bâtit la maison de ses mains", "Builds the house by hand", "Bâton : frappe au sol", "Staff: ground strike",
            "Bâton : tourbillon", "Staff: whirlwind", "Bêche son jardin", "Hoes his garden", "Boit", "Drinks", "Boit un seau de lait", "Drinks a bucket of milk", "Boit une potion", "Drinks a potion",
            "Boitille", "Limps", "Bombe le torse", "Puffs out his chest", "Bonds de grenouille, de plus en plus haut", "Frog leaps, higher and higher", "Bouclier", "Shield", "Boude", "Sulks",
            "Boude, bras croisés", "Sulks, arms crossed", "Boule d'énergie", "Energy ball", "Bowling", "Bowling", "Boxe à vide", "Shadow punches", "Brandit un totem", "Raises a totem",
            "Bras croisés", "Arms crossed", "Bras croisés, tape du pied", "Arms crossed, tapping his foot", "Brasse à sec", "Dry breaststroke", "Burpee", "Burpee", "Câlin", "Hug",
            "Caprice", "Tantrum", "Chaise invisible", "Wall sit", "Chandelle", "Shoulder stand", "Chante au micro", "Sings into a mic", "Charge", "Charge", "Charge de l'épaule", "Shoulder charge",
            "Cherche ses clés dans ses poches", "Looks for his keys", "Choqué", "Shocked", "Chut !", "Shh!", "Claque des doigts", "Snaps his fingers", "Cœur avec les bras", "Heart with his arms",
            "Colère", "Anger", "Combo à l'épée en diamant", "Diamond sword combo", "Compte jusqu'à trois", "Counts to three", "Compte ses émeraudes", "Counts his emeralds",
            "Compte sur ses doigts", "Counts on his fingers", "Concentre son énergie", "Gathers his energy", "Confusion", "Confused", "Corde à sauter", "Jump rope",
            "Coucou à deux mains", "Two-handed wave", "Coucou des deux mains", "Waves with both hands", "Coup de chapeau", "Tips his hat", "Coup de coude", "Elbow strike",
            "Coup de genou", "Knee strike", "Coup de marteau des deux poings", "Double hammer fist", "Coup de pied", "Kick", "Coup de pied arrière", "Back kick", "Coup de pied bas", "Low kick",
            "Coup de pied en ciseaux", "Scissor kick", "Coup de pied en vrille", "Spinning kick", "Coup de pied haut", "High kick", "Coup de pied retourné", "Roundhouse kick",
            "Coup de pied sauté", "Jump kick", "Coup de poing", "Punch", "Coup de poing bas", "Low punch", "Coup de poing haut", "High punch", "Coup de tête", "Headbutt",
            "Coupe du bois à la hache", "Chops wood with an axe", "Course", "Run", "Course au ralenti", "Slow-motion run", "Course en arrière", "Backward run", "Course ninja", "Ninja run",
            "Course paniquée", "Panicked run", "Crawl à sec", "Dry front crawl", "Creuse à la pelle", "Digs with a shovel", "Crochet", "Hook", "Croque une carotte dorée", "Bites a golden carrot",
            "Croque une pomme dorée", "Bites a golden apple", "Danse de la joie", "Happy dance", "Danse de la victoire", "Victory dance", "Demande la parole", "Raises his hand",
            "Démarche cool", "Cool walk", "Démarche de cow-boy", "Cowboy walk", "Départ de sprint", "Sprint start", "Dépité", "Dejected", "Désespoir", "Despair",
            "Désigne quelqu'un du doigt", "Points at someone", "Dessine", "Draws", "Dessine sur l'écran", "Draws on the screen", "Développé au-dessus de la tête", "Overhead press",
            "Devient géant", "Turns giant", "Devient minuscule", "Turns tiny", "Direct en reculant", "Jab while backing off", "DJ", "DJ", "Dort", "Sleeps", "Dort dans un lit", "Sleeps in a bed",
            "Double coup de poing", "Double punch", "Double poing", "Double fist", "Double salto arrière", "Double backflip", "Double salto avant", "Double front flip", "Double saut", "Double jump",
            "Dribble", "Dribble", "Dribble du pied", "Foot dribble", "Enchaînement de 2 coups", "2-hit combo", "Enchaînement de 3 coups", "3-hit combo", "Enchaînement de 5 coups", "5-hit combo",
            "Enchaînement gauche-droite-uppercut", "Left-right-uppercut combo", "Ennui", "Bored", "Envoie un bisou", "Blows a kiss", "Envoie un bisou des deux mains", "Blows a kiss with both hands",
            "Épée : double taille", "Sword: double slash", "Épée : estoc", "Sword: thrust", "Épée : moulinet", "Sword: flourish", "Épée : parade", "Sword: parry",
            "Épée : parade et riposte", "Sword: parry and riposte", "Épée : taille haute", "Sword: high slash", "Épée : taille montante", "Sword: rising slash", "Équerre", "L-sit",
            "Équilibre sur la tête", "Headstand", "Équilibre sur une main", "One-hand handstand", "Escalier de blocs", "Block staircase", "Esquive arrière", "Back dodge", "Esquive basse", "Duck",
            "Esquive en pivotant", "Pivot dodge", "Esquives de boxeur", "Boxer's weave", "Essuie une vitre", "Wipes a window", "Éternue", "Sneezes", "Étire ses quadriceps", "Stretches his quads",
            "Étirement latéral", "Side stretch", "Explore à la torche", "Explores with a torch", "Explose de rire, plié en deux", "Doubles over laughing", "Fabrique une épée sur l'établi", "Crafts a sword at the crafting table",
            "Facepalm", "Facepalm", "Fait craquer ses doigts", "Cracks his knuckles", "Fait des pompes de canard", "Chicken wings", "Fait du stop", "Hitchhikes", "Fait du vélo sur le dos", "Bicycle kicks on his back",
            "Fait la planche contre un mur", "Leans against a wall", "Fait la sieste à la maison", "Takes a nap at home", "Fait la statue", "Plays statue", "Fait la vaisselle", "Does the dishes",
            "Fait l'avion", "Plays airplane", "Fait le signe de la paix", "Peace sign", "Fait le signe du cœur avec les doigts", "Finger heart", "Fait les poussières", "Dusts",
            "Fait non du doigt", "Wags his finger", "Fait ses lacets", "Ties his shoelaces", "Fait signe d'approcher", "Beckons", "Fait signe de partir", "Waves someone away",
            "Fait tournoyer son bâton", "Twirls his staff", "Fait un cadre avec ses mains", "Frames a shot with his hands", "Fentes", "Lunges", "Fentes latérales", "Side lunges",
            "Fentes sautées", "Jump lunges", "Feu d'artifice", "Firework", "Feu de camp", "Campfire", "Fier", "Proud", "Fier comme un coq", "Proud as a peacock",
            "Flâne les mains dans le dos", "Strolls, hands behind his back", "Flip arrière groupé", "Tucked backflip", "Flip-flap", "Back handspring", "Fonce tête baissée", "Charges head down",
            "Fond en larmes", "Bursts into tears", "Fou rire", "Giggle fit", "Freeze de breakdance", "Breakdance freeze", "Frissonne", "Shivers", "Frissonne de froid", "Shivers with cold",
            "Fuite paniquée", "Panicked escape", "Funambule", "Tightrope walk", "Gainage sur un bras", "One-arm plank", "Garde à l'épée", "Sword guard", "Garde basse", "Low guard",
            "Garde basse, feintes", "Low guard, feints", "Garde haute", "High guard", "Garde haute, pas chassés", "High guard, side steps", "Genoux hauts", "High knees",
            "Glissade sur les genoux", "Knee slide", "Glisse et tombe", "Slips and falls", "Grand écart", "Splits", "Grand écart sauté", "Split jump", "Grand jeté", "Grand jeté",
            "Grand salut", "Big wave", "Grand saut", "Big jump", "Grandes enjambées", "Long strides", "Grands moulinets des bras", "Big arm circles", "Grignote un cookie", "Nibbles a cookie",
            "Grimpe", "Climbs", "Grimpe à un mur invisible", "Climbs an invisible wall", "Haltères", "Dumbbells", "Haltérophilie", "Weightlifting", "Hausse les épaules", "Shrugs",
            "Hausse les épaules deux fois", "Shrugs twice", "Hésite, se balance d'un pied sur l'autre", "Hesitates, shifting from foot to foot", "Hoche la tête", "Nods", "Hula hoop", "Hula hoop",
            "Idée !", "Idea!", "Impatient", "Impatient", "Jogging tranquille", "Easy jog", "Joie", "Joy", "Jongle", "Juggles", "Jongle avec un ballon", "Keepy-uppies",
            "Joue à la console", "Plays video games", "Joue au yo-yo", "Plays with a yo-yo", "Joue de la guitare", "Plays the guitar", "Joue du tambour", "Plays the drum",
            "Jubile en silence", "Silent cheer", "Jumelles", "Binoculars", "Jumping jacks", "Jumping jacks", "Kata de karaté", "Karate kata", "Kip-up", "Kip-up",
            "Lance des confettis", "Throws confetti", "Lance le trident", "Throws the trident", "Lance un shuriken", "Throws a shuriken", "Lance une boule de neige", "Throws a snowball",
            "Lance une pièce", "Flips a coin", "Lancer", "Throw", "Lancer de javelot", "Javelin throw", "Lancer de poids", "Shot put", "Lancers francs", "Free throws", "Le ver", "The worm",
            "Lève les bras au ciel", "Throws his arms up", "Lit", "Reads", "Lit le journal assis", "Reads the paper, sitting", "Lit un livre enchanté", "Reads an enchanted book", "Lit une carte", "Reads a map",
            "Mains dans le dos", "Hands behind his back", "Mains en porte-voix", "Shouts through cupped hands", "Mains sur les hanches", "Hands on hips", "Mains sur les hanches (marche)", "Hands on hips (walking)",
            "Mange", "Eats", "Mange du pain", "Eats bread", "Mange un steak", "Eats a steak", "Marche", "Walk", "Marche accroupie", "Crouch walk", "Marche arrière", "Walks backwards",
            "Marche au pas cadencé", "Quick march", "Marche de mannequin", "Catwalk", "Marche décontractée", "Relaxed walk", "Marche lente", "Slow walk", "Marche lourde", "Heavy walk",
            "Marche militaire", "Military march", "Marche pressée, penché en avant", "Hurried walk, leaning forward", "Marche rapide", "Fast walk", "Marche sur des œufs", "Walks on eggshells",
            "Marche sur les genoux", "Walks on his knees", "Marche sur les mains", "Walks on his hands", "Marteau géant", "Giant hammer", "Méditation", "Meditation", "Mime une vitre", "Mimes a glass wall",
            "Mine avec une pioche", "Mines with a pickaxe", "Montées de genoux", "Knee raises", "Montre ses biceps", "Flexes his biceps", "Montre ses muscles", "Shows off his muscles",
            "Moonwalk", "Moonwalk", "Moulin à vent", "Windmill", "Moulin à vent, mains aux pieds", "Windmill toe touches", "Mouline d'un seul bras", "One-arm windmill",
            "Moulinet du poignet", "Wrist twirl", "Moulinets de hanches", "Hip circles", "Moulinets de poings", "Fist circles", "Mountain climbers", "Mountain climbers", "Nage", "Swims",
            "Non du doigt", "Finger wag", "Noue sa cravate", "Ties his tie", "Nunchaku", "Nunchaku", "Observe à la longue-vue", "Looks through a spyglass", "Onde de choc", "Shockwave",
            "Ouvre YouTube sur la chaîne d'Alan Becker", "Opens Alan Becker's YouTube channel", "Panique, court sur place", "Panics, running on the spot", "Parade haute puis basse", "High then low block",
            "Parapluie", "Umbrella", "Pas de géant", "Giant steps", "Pas de géant, lents", "Slow giant steps", "Pas de loup", "Tiptoes stealthily", "Pas de parade", "Parade step",
            "Passe l'aspirateur", "Vacuums", "Patinage", "Skating", "Pêche depuis le bord", "Fishes from the edge", "Pédale", "Pedals", "Peint un mur au rouleau", "Paints a wall with a roller",
            "Penalty", "Penalty kick", "Perle de l'Ender", "Ender pearl", "Petit trot", "Trot", "Petits pas pressés", "Quick little steps", "Peur", "Fear", "Planche", "Plank",
            "Planche faciale", "Front lever", "Plante des fleurs", "Plants flowers", "Pleure", "Cries", "Plongeon roulé", "Dive roll", "Pluie de coups de pied", "Flurry of kicks",
            "Poing du dragon", "Dragon punch", "Poing levé", "Raised fist", "Pointe derrière", "Points behind", "Pointe devant", "Points ahead", "Pointe en haut", "Points up",
            "Poirier", "Handstand", "Pompes", "Push-ups", "Pompes en équilibre", "Handstand push-ups", "Pompes sur un bras", "One-arm push-ups", "Pont arrière", "Back bridge",
            "Portail du Nether", "Nether portal", "Porte un carton lourd", "Carries a heavy box", "Porte un plateau", "Carries a tray", "Porte un toast", "Raises a toast",
            "Pouce en l'air", "Thumbs up", "Pouces en l'air des deux mains", "Two thumbs up", "Prend un selfie", "Takes a selfie", "Prend une photo", "Takes a photo",
            "Prise et projection", "Grab and throw", "Provocation", "Taunt", "Rafale de coups de poing", "Flurry of punches", "Rafale de directs", "Flurry of jabs", "Rage", "Rage",
            "Ramasse quelque chose", "Picks something up", "Ramasse quelque chose par terre", "Picks something up off the ground", "Rame en bateau", "Rows a boat", "Rameur", "Rowing machine",
            "Rampe", "Crawls", "Rayon d'énergie", "Energy beam", "Réfléchit", "Thinks", "Regarde au loin", "Looks into the distance", "Regarde en bas", "Looks down",
            "Regarde le ciel", "Looks at the sky", "Regarde l'heure", "Checks the time", "Regarde sa boussole", "Checks his compass", "Regarde sa montre", "Checks his watch",
            "Regarde ses pieds", "Looks at his feet", "Rentre à la maison", "Goes home", "Repasse une chemise", "Irons a shirt", "Reprend son souffle", "Catches his breath",
            "Rêvasse, la tête dans les nuages", "Daydreams, head in the clouds", "Révérence profonde", "Deep bow", "Rit", "Laughs", "Rondade flip", "Round-off flip", "Roue", "Cartwheel",
            "Roue arrière", "Back cartwheel", "Roue sans les mains", "No-hands cartwheel", "Roue sur un bras", "One-arm cartwheel", "Roulade arrière", "Backward roll", "Roulade avant", "Forward roll",
            "Roulade d'esquive", "Dodge roll", "Roule en boule", "Rolls into a ball", "Roule en wagonnet", "Rides a minecart", "Salto arrière", "Backflip", "Salto avant", "Front flip",
            "Salto tendu", "Layout flip", "Salto vrillé", "Twisting flip", "Salue comme une reine", "Royal wave", "Salut", "Wave", "Salut du combattant", "Fighter's bow",
            "Salut martial", "Martial salute", "Salut militaire", "Military salute", "Salut timide", "Shy wave", "S'appuie sur son bâton", "Leans on his staff", "S'assoit", "Sits down",
            "Saut", "Jump", "Saut carpé", "Pike jump", "Saut carpé jambes écartées", "Straddle jump", "Saut de chat", "Cat leap", "Saut de l'ange", "Swan dive", "Saut de main", "Handspring",
            "Saut de mains", "Front handspring", "Saut écart", "Star split jump", "Saut en étoile", "Star jump", "Saut en longueur", "Long jump", "Saut en longueur sur place", "Standing long jump",
            "Saut groupé", "Tuck jump", "Saut groupé-tendu", "Tuck then stretch jump", "Saute à la corde invisible", "Skips an invisible rope", "Saute de joie en tournant", "Jumps for joy, spinning",
            "Saute de joie, bras en V", "Jumps for joy, arms in a V", "Saute de surprise et retombe assis", "Jumps in surprise and lands sitting", "Sautille", "Hops", "Sautille d'excitation", "Bounces with excitement",
            "Sautille en garde", "Bounces on guard", "Sauts de grenouille", "Frog jumps", "Se balance", "Sways", "Se brosse les dents", "Brushes his teeth", "Se cache les yeux", "Covers his eyes",
            "Se chauffe les mains", "Warms his hands", "Se frotte le ventre", "Rubs his belly", "Se frotte les mains", "Rubs his hands", "Se frotte les yeux", "Rubs his eyes",
            "Se gratte la nuque", "Scratches his neck", "Se gratte la tête", "Scratches his head", "Se gratte le menton", "Scratches his chin", "Se prend la tête à deux mains", "Holds his head in both hands",
            "Se recoiffe", "Fixes his hair", "Se ronge les ongles", "Bites his nails", "Se tape le front", "Slaps his forehead", "Seau d'eau au dernier moment", "Last-second water bucket",
            "Secoue sa fenêtre", "Shakes his window", "Service de tennis", "Tennis serve", "S'étire", "Stretches", "S'étire au réveil", "Wake-up stretch", "S'évente de la main", "Fans himself",
            "Shadow-boxing en sautillant", "Bouncing shadow-boxing", "Shoote dans un caillou", "Kicks a pebble", "Shuffle", "Shuffle", "Sieste sur le ventre", "Naps on his belly", "Siffle", "Whistles",
            "S'incline", "Bows", "S'incline, vaincu", "Bows, defeated", "Skateboard", "Skateboard", "Ski (schuss)", "Skiing (tuck)", "Smash de volley", "Volleyball spike",
            "Sonne la cloche", "Rings the bell", "Souffle dans une corne", "Blows a horn", "Soulève un chapeau invisible", "Tips an invisible hat", "Soupir de soulagement", "Sigh of relief",
            "Soupire", "Sighs", "Sprint", "Sprint", "Sprint à fond", "Full sprint", "Squats", "Squats", "Squats sautés", "Jump squats", "Stop", "Stop", "Supplie", "Begs",
            "Sur la pointe des pieds", "On tiptoe", "Surexcité", "Overexcited", "Surf", "Surfing", "Surprise", "Surprise", "Sursaute de peur", "Jumps with fright", "Swing de golf", "Golf swing",
            "Tai-chi", "Tai chi", "Talons-fesses", "Butt kicks", "Tape au clavier", "Types on a laptop", "Tape des mains au-dessus de la tête", "Claps above his head", "Tape du pied", "Taps his foot",
            "Tape du poing dans sa main", "Pounds his fist into his palm", "Tape sur un clavier debout", "Types standing up", "Tape un arbre à mains nues", "Punches a tree", "Tape un texto", "Texts",
            "Téléphone", "On the phone", "Tend l'oreille", "Cups his ear", "Timide", "Shy", "Timide, se tortille", "Shy, squirming", "Tir à l'arc", "Archery", "Tir au but", "Shot on goal",
            "Tir au panier", "Jump shot", "Titube", "Staggers", "TNT", "TNT", "Tombe à la renverse de surprise", "Falls over backwards in surprise", "Touche ses orteils", "Touches his toes",
            "Touche ses pieds", "Reaches for his feet", "Toupie de combat", "Spinning attack", "Toupie sur la tête", "Head spin", "Tour de blocs", "Block tower", "Tousse", "Coughs",
            "Tractions", "Pull-ups", "Trampoline de slime", "Slime trampoline", "Trébuche", "Trips", "Tremble de peur", "Trembles with fear", "Trépigne d'impatience", "Stamps impatiently",
            "Triomphe à genoux", "Triumphs on his knees", "Triple salto", "Triple flip", "Tristesse", "Sadness", "Trotte en sifflotant", "Trots along whistling", "Trottine sur la pointe", "Trots on tiptoe",
            "Twist des genoux", "Knee twist", "Uppercut", "Uppercut", "Uppercut sauté", "Jumping uppercut", "V de la victoire", "V for victory", "Vague du corps", "Body wave", "Victoire", "Victory",
            "Viens ici", "Come here", "Visse une ampoule", "Screws in a light bulb", "Vol en élytres", "Elytra flight", "Vole comme un super-héros", "Flies like a superhero", "Yes !", "Yes!",
            "Yoga : chien tête en bas", "Yoga: downward dog", "Yoga : la chandelle", "Yoga: shoulder stand", "Yoga : l'arbre", "Yoga: tree", "Yoga : le cobra", "Yoga: cobra",
            "Yoga : le guerrier", "Yoga: warrior", "Zombie", "Zombie",

            // ---------------------------------------------------------------- huitième fournée
            "Animations spéciales", "Special tricks",
            "Tchin !", "Cheers!", "Santé !", "Cheers!", "Ahh…", "Ahh…", "Check du pied", "Foot tap", "Du pied !", "Foot bump!",
            "Garde-à-vous", "Stand to attention", "Garde à vous !", "Attention!", "Chef, oui chef !", "Sir, yes sir!", "Repos.", "At ease.",
            "La ola", "The wave", "Olaaa !", "Whoooa!", "Trop lent !", "Too slow!", "Concours de pompes", "Push-up contest", "Concours de pompes !", "Push-up contest!",
            "Tu vas perdre !", "You're going down!", "Je suis mort…", "I'm dead…",
            "Marche de pingouin", "Penguin walk", "Course de dessin animé", "Cartoon run", "Trottine, les bras en l'air", "Trots with his arms in the air", "Robot rouillé", "Rusty robot",
            "Promenade du dimanche", "Sunday stroll", "Marche contre le vent", "Walks against the wind", "Traîne les pieds, épuisé", "Drags his feet, worn out",
            "Avance en faisant la roue", "Cartwheels along", "Glisse sur le ventre comme un pingouin", "Slides on his belly like a penguin", "Ski de fond", "Cross-country skiing",
            "Sautille à pieds joints", "Hops with both feet", "Galope sur un cheval invisible", "Gallops on an invisible horse", "Marche du crabe", "Crab walk",
            "Chasse une mouche", "Swats a fly", "Se bouche le nez", "Holds his nose", "Salue derrière lui", "Waves behind him", "Moulinets inversés", "Opposite windmills",
            "Pistolets des doigts", "Finger guns", "Lance un avion en papier", "Throws a paper plane", "Se dépoussière l'épaule", "Dusts off his shoulder",
            "Joue de la flûte", "Plays the flute", "Joue du violon", "Plays the violin", "Joue de la trompette", "Plays the trumpet", "Joue de l'accordéon", "Plays the accordion",
            "Fait de grands signes", "Waves both arms wildly", "Se bouche les oreilles", "Covers his ears", "Motus et bouche cousue", "Zips his lips", "Se tapote la tempe", "Taps his temple",
            "Double coup de pied sauté", "Jumping double kick", "Coup de genou sauté", "Jumping knee", "Blocage et contre", "Block and counter", "Coup de pied de la grue", "Crane kick",
            "Coup de pied marteau", "Axe kick", "Frappe de la paume", "Palm strike", "Salto arrière frappé", "Flash kick", "Esquive en se penchant en arrière", "Leans back to dodge",
            "Coup de pied bas puis haut", "Low kick then high kick", "Garde serrée derrière ses gants", "Tight guard behind his gloves", "Charge son poing, puis frappe", "Charges his fist, then strikes",
            "Roue puis salto", "Cartwheel into a flip", "Saut de biche", "Stag leap", "Poirier, grand écart", "Handstand splits", "Rebondit sur les fesses", "Bounces on his bottom",
            "Salto raté, atterrit sur le dos", "Botched flip, lands on his back", "Deux roues enchaînées", "Two cartwheels in a row",
            "Manchette de volley", "Volleyball dig", "Lancer de fléchettes", "Darts", "Revers de tennis", "Tennis backhand", "Putt de golf", "Golf putt", "Lancer du disque", "Discus throw",
            "Plongeon de gardien", "Goalkeeper dive", "Lutte à la corde", "Tug of war", "Escrime : fente", "Fencing: lunge", "Smash de badminton", "Badminton smash",
            "Rotations du buste", "Torso twists", "Saut de haies", "Hurdle jump", "Pétanque : pointe", "Pétanque: rolls the boule", "Kayak", "Kayak",
            "Fait sauter une crêpe", "Flips a pancake", "Scie une planche", "Saws a plank", "Tond la pelouse", "Mows the lawn", "Souffle ses bougies", "Blows out his candles",
            "Enfile un pull", "Pulls on a jumper", "Enfile une chaussure à cloche-pied", "Puts on a shoe, hopping", "Gonfle un pneu", "Pumps up a tyre", "Tire sur un démarreur", "Pulls a starter cord",
            "Secoue un shaker", "Shakes a cocktail", "Étend le linge", "Hangs out the washing", "Pique du nez debout", "Nods off standing up", "Cherche du réseau", "Looks for a signal",
            "Se mouche", "Blows his nose", "S'admire dans un miroir", "Admires himself in a mirror", "Pousse un meuble lourd", "Pushes heavy furniture",
            "S'évanouit", "Faints", "Hurle au ciel", "Screams at the sky", "Se roule par terre de rire", "Rolls on the floor laughing", "Flotte sur un petit nuage", "Walks on air",
            "Gêné, se frotte le bras", "Embarrassed, rubs his arm", "Dégoûté, repousse des mains", "Disgusted, pushes it away", "Émerveillé, les mains sur les joues", "Amazed, hands on his cheeks",
            "Se frappe la poitrine", "Thumps his chest", "Claque des talons en sautant", "Clicks his heels in the air", "Épuisé, s'affale par terre", "Exhausted, flops to the ground",
            "Curieux, regarde par le trou de la serrure", "Curious, peeks through the keyhole",
            "Chorégraphie de la Macarena", "Macarena routine", "Charleston", "Charleston", "Danse du cavalier", "Horse-riding dance", "Valse", "Waltz", "Kazatchok", "Cossack dance",
            "French cancan", "Can-can", "Sirtaki", "Sirtaki", "Hula hawaïen", "Hawaiian hula", "Flamenco", "Flamenco", "Claquettes", "Tap dance", "Pogo", "Pogo", "Headbang", "Headbang",
            "Slow tout seul", "Slow dance on his own", "Limbo", "Limbo", "Running man", "Running man", "Haka", "Haka",
            "Mange une part de pastèque", "Eats a melon slice", "Mange une tarte à la citrouille", "Eats a pumpkin pie", "Croque une pomme", "Bites an apple", "Mange un gâteau", "Eats a cake",
            "Boit une soupe de champignons", "Drinks mushroom stew", "Boit une bouteille de miel", "Drinks a honey bottle", "Lance un œuf", "Throws an egg", "Lance sa ligne", "Casts his line",
            "Lève son épée en netherite", "Raises his netherite sword", "Danse avec un disque", "Dances with a music disc", "Écrit dans son livre", "Writes in his book",
            "Frotte son briquet", "Strikes his flint and steel", "Fait sauter un lingot d'or dans sa main", "Tosses a gold ingot in his hand", "Brandit une étoile du Nether", "Raises a Nether star",
            "Lance un œil de l'Ender", "Throws an eye of Ender", "Coupe aux cisailles", "Snips with shears", "Fouille à la brosse", "Brushes for treasure",
            "Avance, une carotte au bout du bâton", "Walks with a carrot on a stick", "Promène son poisson dans un seau", "Takes his fish for a walk in a bucket",

            // ---------------------------------------------------------------- neuvième fournée
            // (les enchaînements « A + B » et les « … au ralenti » se traduisent tout seuls, morceau par morceau)
            "…", "…",
            "Pluie", "Rain", "Pêche à la ligne", "Fishing", "Caddie", "Shopping cart", "Pousse le plafond", "Raise the roof", "Poing qui pompe", "Fist pump", "Bisous", "Blowing kisses",
            "Batterie", "Drums", "Mains sur la tête", "Hands on head", "Ciseaux", "Scissors", "Balancier", "Pendulum", "Chef d'orchestre", "Conductor", "Thriller", "Thriller",
            "genoux", "knees", "charleston", "charleston", "accroupi", "squat kicks",
            "Soldat de plomb", "Tin soldier", "Trot de poney", "Pony trot", "Ninja accroupi", "Crouching ninja", "Marche nordique", "Nordic walking", "Pas de l'oie", "Goose step",
            "Petite foulée", "Easy jog", "Marche du penseur", "Thinker's walk", "Défilé, mains sur les hanches", "Struts with his hands on his hips", "Randonneur chargé", "Loaded hiker",
            "Promène un chien invisible", "Walks an invisible dog", "Marche le nez sur son téléphone", "Walks glued to his phone", "Marche en lisant un livre", "Walks while reading a book",
            "Se promène sous son parapluie", "Strolls under his umbrella", "Défile en majorette", "Marches like a majorette",
            "Se gratte le dos", "Scratches his back", "Shaka", "Shaka", "Attrape une mouche au vol", "Catches a fly in mid-air", "Regarde s'il pleut", "Checks if it's raining",
            "Pouce vers le bas", "Thumbs down", "Garde du tigre", "Tiger stance", "Lance un frisbee", "Throws a frisbee", "Trampoline", "Trampoline", "Étire ses mollets", "Stretches his calves",
            "Slalom à ski", "Ski slalom", "Rodéo", "Rodeo", "Range en haut d'une étagère", "Tidies the top shelf", "Frappe à une porte", "Knocks on a door", "Appelle l'ascenseur", "Calls the lift",
            "Arrache une mauvaise herbe", "Pulls out a weed", "Se brûle avec son café", "Burns himself on his coffee", "L'air innocent, sifflote", "Whistles innocently",
            "Prie pour que ça marche", "Prays that it works", "Se fait tout petit", "Makes himself tiny", "Exaspéré, lève les yeux au ciel", "Exasperated, rolls his eyes",
            "Se retient, danse d'un pied sur l'autre", "Holding it in, hops from foot to foot", "S'époussette les mains, travail fini", "Dusts off his hands, job done",
            "Mange un poulet rôti", "Eats a roast chicken", "Mange une pomme de terre cuite", "Eats a baked potato", "Mange une côtelette", "Eats a pork chop", "Mange un saumon grillé", "Eats cooked salmon",
            "Mange du mouton rôti", "Eats roast mutton", "Mange une morue grillée", "Eats cooked cod", "Grignote des baies sucrées", "Nibbles sweet berries", "Grignote des baies lumineuses", "Nibbles glow berries",
            "Mâchouille du varech séché", "Chews dried kelp", "Croque une betterave", "Bites a beetroot", "Croque une carotte", "Bites a carrot", "Mange un ragoût de lapin", "Eats rabbit stew",
            "Goûte une soupe suspecte", "Tastes a suspicious stew", "Admire un éclat d'améthyste", "Admires an amethyst shard", "Admire un cœur de la mer", "Admires a heart of the sea",
            "Admire un lingot de netherite", "Admires a netherite ingot", "Admire une perle de l'Ender", "Admires an Ender pearl", "Écoute la mer dans un coquillage", "Listens to the sea in a shell",
            "Se chatouille avec une plume", "Tickles himself with a feather", "Fait rebondir une boule de slime", "Bounces a slime ball", "Porte un seau de lave à bout de bras", "Carries a lava bucket at arm's length",
            "Sème des graines", "Sows seeds", "Montre sa récolte de blé", "Shows off his wheat harvest", "Saupoudre de la redstone", "Sprinkles redstone", "Répand de la poudre d'os", "Spreads bone meal",
            "Lit une feuille de papier", "Reads a sheet of paper", "Regarde au fond de son seau", "Peers into his bucket", "Mine avec une pioche en fer", "Mines with an iron pickaxe",
            "Mine avec une pioche en or", "Mines with a golden pickaxe", "Mine avec une pioche en netherite", "Mines with a netherite pickaxe", "Fend l'air avec une épée en fer", "Slashes with an iron sword",
            "Fend l'air avec une épée en or", "Slashes with a golden sword", "Frappe le sol avec une masse", "Smashes the ground with a mace", "Agite un bâton de blaze", "Waves a blaze rod",

            // ---------------------------------------------------------------- dixième fournée
            "Tire la corde", "Rope pull", "Soleil", "Sun circles", "fentes", "lunges",
            "Assis au bord, lit un livre", "Sitting on the edge, reading a book", "Assis au bord, joue de la guitare", "Sitting on the edge, playing the guitar",
            "Assis au bord, casse la croûte", "Sitting on the edge, having a snack", "Assis au bord, fait coucou en bas", "Sitting on the edge, waving down",
            "Assis au bord, pianote sur son téléphone", "Sitting on the edge, tapping on his phone", "Assis au bord, s'étire", "Sitting on the edge, stretching",
            "Assis au bord, pique du nez", "Sitting on the edge, nodding off", "Assis au bord, lance des cailloux", "Sitting on the edge, throwing pebbles",
            "Guette l'horizon du haut de sa fenêtre", "Scans the horizon from his window",
            "Marathonien épuisé", "Exhausted marathon runner", "Patine à reculons", "Skates backwards", "Marche sur des braises", "Walks on hot coals",
            "Pirate à jambe de bois", "Peg-leg pirate", "Flotte comme un fantôme", "Floats like a ghost",
            "Hèle un taxi", "Hails a taxi", "Main sur le cœur", "Hand on his heart", "Robot en panne", "Robot breaking down", "Tour de magie", "Magic trick",
            "Fait craquer son cou", "Cracks his neck", "Tend la main", "Holds out his hand", "Double uppercut", "Double uppercut", "Saute par-dessus sa jambe", "Jumps over his own leg",
            "Frappe de baseball", "Baseball swing", "Curling", "Curling", "Billard", "Pool", "Ping-pong", "Table tennis", "Soulevé de terre", "Deadlift",
            "Fait un château de sable", "Builds a sandcastle", "Flotte sur le dos", "Floats on his back", "Se réveille en sursaut", "Wakes up with a start",
            "Regarde sa montre et panique", "Checks his watch and panics", "Passe la serpillière", "Mops the floor",
            "Assis sur un bloc, s'ennuie", "Sitting on a block, bored", "Assis sur un bloc, le menton dans la main", "Sitting on a block, chin in hand",
            "Assis sur un bloc, balance les pieds", "Sitting on a block, swinging his feet",
            "Bondit comme un cabri", "Leaps about like a kid goat", "Tombe à genoux, désespéré", "Falls to his knees in despair", "Méfiant, jette des coups d'œil", "Wary, glancing around",
            "Essuie une larme", "Wipes away a tear",
            "Fait griller un poulet", "Roasts a chicken", "Ça sent bon…", "Smells good…", "Oups… trop cuit.", "Oops… overcooked.", "À table !", "Dinner's ready!",
            "Applaudissements", "Applause", "Bravo !", "Bravo!", "Bravo à toi !", "Well done you!", "Bras de fer", "Pushing contest", "On pousse !", "Push!",
            "Tu ne passeras pas !", "You won't get past me!", "Trop fort !", "Too strong!", "Hé, doucement !", "Hey, easy!", "Coup d'épaule sauté", "Jumping shoulder bump", "Ouais !", "Yeah!",
            "Tape-mains", "Patty-cake", "Un, deux, trois…", "One, two, three…", "…soleil !", "…go!", "Dispute et réconciliation", "Quarrel and make up",
            "C'est ta faute !", "It's your fault!", "Non, la tienne !", "No, yours!", "Pardon…", "Sorry…", "Moi aussi…", "Me too…",

            // ---------------------------------------------------------------- onzième fournée
            "Ils ont une maison (elle apparaît près de chez eux)", "They have a house (it appears near their home)", "Ils ont une maison", "They have a house",
            "Chouette, une maison !", "Great, a house!", "D'accord, plus de maison.", "All right, no more house.",
            "La maison est désactivée (clic droit pour la remettre)", "The house is switched off (right-click to bring it back)",
            "Bâtit un golem de neige", "Builds a snow golem", "Fait pousser un arbre", "Grows a tree", "Salut, toi !", "Hello, you!", "Il a bien poussé !", "It grew nicely!",
            "Pagaie", "Paddle", "Confettis", "Confetti", "pointes", "toe taps",
            "Apporte un plat à bout de bras", "Carries a dish at arm's length", "Pousse un chariot", "Pushes a trolley", "Marche sur les talons", "Walks on his heels",
            "Court après son chapeau", "Runs after his hat", "S'en va à reculons en saluant", "Backs away, waving",
            "Chasse la fumée de la main", "Waves the smoke away", "Renifle une bonne odeur", "Sniffs something tasty", "Fait signe que non, des deux mains", "Waves no with both hands",
            "Se tourne les pouces", "Twiddles his thumbs", "Salue le public", "Bows to the audience", "Coup de coude complice", "Knowing nudge",
            "Se brûle la langue", "Burns his tongue", "Souffle sur sa soupe", "Blows on his soup", "Met la table", "Lays the table", "Épluche des légumes", "Peels vegetables",
            "Touille la marmite", "Stirs the pot", "Ouvre un cadeau", "Opens a present", "Zappe avec la télécommande", "Flicks through the channels", "Accroche un tableau", "Hangs a picture",
            "Souffle dans ses mains", "Blows into his hands", "Assis sur un bloc, s'étire", "Sitting on a block, stretching", "Assis sur un bloc, tape du pied", "Sitting on a block, tapping his foot",
            "Affamé, se tient le ventre", "Starving, holds his stomach", "Repu, se tapote le ventre", "Full, pats his belly", "Siffle d'admiration", "Whistles in admiration",
            "Souffle sur les flammes, paniqué", "Blows on the flames in a panic", "Cambre le dos", "Arches his back", "Gardien sur sa ligne", "Goalkeeper on his line",
            "Sort un carton rouge", "Shows a red card", "Échauffe ses poignets", "Warms up his wrists",
            "Croque une pomme dorée enchantée", "Bites an enchanted golden apple", "Mange un poisson-globe (mauvaise idée)", "Eats a pufferfish (bad idea)", "Agite un os", "Waves a bone",
            "S'éclaire à la bougie", "Lights his way with a candle",

            // ---------------------------------------------------------------- douzième fournée
            "Vitres", "Window cleaning", "Cloche", "Bell ringing", "ruades", "back kicks",
            "Écrit au tableau", "Writes on the board", "Efface le tableau", "Wipes the board", "Fait tourner son stylo", "Spins his pen",
            "Assis sur un bloc, s'endort", "Sitting on a block, falling asleep", "Cartable trop lourd", "Schoolbag far too heavy", "File à la récré", "Dashes off to break",
            "Manette en main", "Controller in hand", "Rage quit", "Rage quit", "Imite un singe", "Does a monkey impression", "Imite un flamant rose", "Does a flamingo impression",
            "Marche du gorille", "Gorilla walk", "Bonds de kangourou", "Kangaroo hops", "Montre les étoiles, allongé", "Lies back and points at the stars",
            "Fait des ricochets", "Skims stones", "Cueille un fruit", "Picks a fruit", "Souffle sur un pissenlit", "Blows on a dandelion", "Saut de précision", "Precision jump",
            "Yoga : salutation au soleil", "Yoga: sun salutation", "Outré, les poings sur les hanches", "Outraged, fists on his hips", "Ricane dans sa main", "Sniggers into his hand",

            // ---------------------------------------------------------------- treizième fournée : paysages, tours spéciaux
            "Des paysages de blocs apparaissent (colline, mine, ferme, mare…)", "Block landscapes appear (hill, mine, farm, pond…)", "Paysages de blocs", "Block landscapes",
            "Les paysages sont désactivés (clic droit pour les remettre)", "Landscapes are switched off (right-click to bring them back)",
            "Paysage : colline fleurie", "Landscape: flowery hill", "Paysage : mine de diamants", "Landscape: diamond mine", "Paysage : ferme", "Landscape: farm",
            "Paysage : portail en ruine", "Landscape: ruined portal", "Paysage : mare", "Landscape: pond",
            "Un vieux portail…", "An old portal…", "Des diamants !", "Diamonds!", "Joli coin !", "Nice spot!",
            "Il se dédouble : deux reflets dansent avec lui", "He splits in three: two reflections dance with him", "Il passe en arc-en-ciel un moment", "He turns rainbow for a while",
            "Il devient presque invisible et se faufile", "He turns almost invisible and sneaks about", "Apesanteur : il flotte en l'air", "Zero gravity: he floats in the air",
            "Il prend feu et court partout (pour rire)", "He catches fire and runs around (just for fun)",
            "Se dédouble", "Splits in three", "Passe en arc-en-ciel", "Turns rainbow", "Devient presque invisible", "Turns almost invisible", "Apesanteur", "Zero gravity",
            "Prend feu (pour rire)", "Catches fire (just for fun)", "On est trois !", "There are three of us!", "Toutes les couleurs !", "All the colours!",
            "Vous ne me voyez plus…", "You can't see me now…", "Coucou !", "Peekaboo!", "Plus de gravité !", "No more gravity!", "Ouf, le sol.", "Phew, the ground.",
            "Chaud ! Chaud ! Chaud !", "Hot! Hot! Hot!", "Ouf… éteint.", "Phew… it's out.",
            "Tambourin", "Tambourine", "Bras en croix", "Arms spread", "sautillés", "skips",
            "Lance un boomerang", "Throws a boomerang", "Remonte un gros poisson", "Reels in a big fish", "Plante son drapeau, conquérant", "Plants his flag, triumphant",
            "Saute dans les flaques", "Jumps in puddles", "Suit un papillon des yeux", "Watches a butterfly", "Contemple l'horizon, assis", "Sits and gazes at the horizon",
            "S'abrite sous ses mains", "Shelters under his hands", "Sieste adossé", "Naps leaning back", "Lance des graines aux oiseaux", "Throws seeds to the birds",
            "Empile des cailloux", "Stacks pebbles",
        };
    }
}
